name: Gauge e2e tests

# trigger e2e test run when pre-release is created
on: [pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        sudo apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-keys 023EDB0B
        echo deb https://dl.bintray.com/gauge/gauge-deb stable main | sudo tee -a /etc/apt/sources.list
        sudo apt-get update
        sudo apt-get install gauge
        gauge install
        npm ci
    - name: Run tests
      run: |
        npm run automated | tee reports/logs/stdout.log
      env:
        CI: true
        SUITEST_TEST_PACK_ID: ${{ secrets.TEST_PACK_ID }}
        SUITEST_TOKEN_KEY: ${{ secrets.TOKEN_KEY }}
        SUITEST_TOKEN_PASSWORD: ${{ secrets.TOKEN_PASSWORD }}
      continue-on-error: true
    - name: Report results to dashboard
      run: |
        curl -X POST -H "x-api-key:${{ secrets.CALLIOPE_TOKEN }}" -H "Content-Type:application/*" --data "@reports/xml-report/result.xml" "https://app.calliope.pro/api/v2/profile/764/report/import/junit"
      continue-on-error: true
    - name: Archive the reports and save them as artifact
      uses: actions/upload-artifact@v1
      with:
        name: Report
        path: reports
